# Generated by Django 5.0.1 on 2024-01-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_disliked_by_post_liked_by_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email_hash',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
